//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInst", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.ArrayOfAnyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.TaskAttach[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.TaskAttach))]
    public partial class TaskInst : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.ArrayOfAnyType _arrsqlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurOrgIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WFCatCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WFCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceTaskNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.ArrayOfString DetailTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFieldsXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarFieldsXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostUserAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskMemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskTopicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.TaskAttach[] TaskAttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FormContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.ArrayOfAnyType ArrExecSqlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsoleApplication1.ServiceReference1.ArrayOfAnyType _arrsql {
            get {
                return this._arrsqlField;
            }
            set {
                if ((object.ReferenceEquals(this._arrsqlField, value) != true)) {
                    this._arrsqlField = value;
                    this.RaisePropertyChanged("_arrsql");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PurOrgID {
            get {
                return this.PurOrgIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PurOrgIDField, value) != true)) {
                    this.PurOrgIDField = value;
                    this.RaisePropertyChanged("PurOrgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WFCatCD {
            get {
                return this.WFCatCDField;
            }
            set {
                if ((object.ReferenceEquals(this.WFCatCDField, value) != true)) {
                    this.WFCatCDField = value;
                    this.RaisePropertyChanged("WFCatCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string WFCD {
            get {
                return this.WFCDField;
            }
            set {
                if ((object.ReferenceEquals(this.WFCDField, value) != true)) {
                    this.WFCDField = value;
                    this.RaisePropertyChanged("WFCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NodeCD {
            get {
                return this.NodeCDField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeCDField, value) != true)) {
                    this.NodeCDField = value;
                    this.RaisePropertyChanged("NodeCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskIDField, value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SourceTaskNo {
            get {
                return this.SourceTaskNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceTaskNoField, value) != true)) {
                    this.SourceTaskNoField = value;
                    this.RaisePropertyChanged("SourceTaskNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SourceSystem {
            get {
                return this.SourceSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceSystemField, value) != true)) {
                    this.SourceSystemField = value;
                    this.RaisePropertyChanged("SourceSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ConsoleApplication1.ServiceReference1.ArrayOfString DetailTables {
            get {
                return this.DetailTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailTablesField, value) != true)) {
                    this.DetailTablesField = value;
                    this.RaisePropertyChanged("DetailTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string DataFieldsXML {
            get {
                return this.DataFieldsXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFieldsXMLField, value) != true)) {
                    this.DataFieldsXMLField = value;
                    this.RaisePropertyChanged("DataFieldsXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string VarFieldsXML {
            get {
                return this.VarFieldsXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.VarFieldsXMLField, value) != true)) {
                    this.VarFieldsXMLField = value;
                    this.RaisePropertyChanged("VarFieldsXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PostUserAccount {
            get {
                return this.PostUserAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.PostUserAccountField, value) != true)) {
                    this.PostUserAccountField = value;
                    this.RaisePropertyChanged("PostUserAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string TaskMemo {
            get {
                return this.TaskMemoField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskMemoField, value) != true)) {
                    this.TaskMemoField = value;
                    this.RaisePropertyChanged("TaskMemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TaskTopic {
            get {
                return this.TaskTopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskTopicField, value) != true)) {
                    this.TaskTopicField = value;
                    this.RaisePropertyChanged("TaskTopic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string TaskPriority {
            get {
                return this.TaskPriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskPriorityField, value) != true)) {
                    this.TaskPriorityField = value;
                    this.RaisePropertyChanged("TaskPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ConsoleApplication1.ServiceReference1.TaskAttach[] TaskAttachments {
            get {
                return this.TaskAttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskAttachmentsField, value) != true)) {
                    this.TaskAttachmentsField = value;
                    this.RaisePropertyChanged("TaskAttachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string FormType {
            get {
                return this.FormTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FormTypeField, value) != true)) {
                    this.FormTypeField = value;
                    this.RaisePropertyChanged("FormType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public byte[] FormContent {
            get {
                return this.FormContentField;
            }
            set {
                if ((object.ReferenceEquals(this.FormContentField, value) != true)) {
                    this.FormContentField = value;
                    this.RaisePropertyChanged("FormContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public ConsoleApplication1.ServiceReference1.ArrayOfAnyType ArrExecSql {
            get {
                return this.ArrExecSqlField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrExecSqlField, value) != true)) {
                    this.ArrExecSqlField = value;
                    this.RaisePropertyChanged("ArrExecSql");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string AttachType {
            get {
                return this.AttachTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachTypeField, value) != true)) {
                    this.AttachTypeField = value;
                    this.RaisePropertyChanged("AttachType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskAttach", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaskAttach : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BindControlIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ConnectionID {
            get {
                return this.ConnectionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionIDField, value) != true)) {
                    this.ConnectionIDField = value;
                    this.RaisePropertyChanged("ConnectionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] FileContent {
            get {
                return this.FileContentField;
            }
            set {
                if ((object.ReferenceEquals(this.FileContentField, value) != true)) {
                    this.FileContentField = value;
                    this.RaisePropertyChanged("FileContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BindControlID {
            get {
                return this.BindControlIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BindControlIDField, value) != true)) {
                    this.BindControlIDField = value;
                    this.RaisePropertyChanged("BindControlID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WFServiceSoap")]
    public interface WFServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Submit", ReplyAction="*")]
        ConsoleApplication1.ServiceReference1.SubmitResponse Submit(ConsoleApplication1.ServiceReference1.SubmitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Submit", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.SubmitResponse> SubmitAsync(ConsoleApplication1.ServiceReference1.SubmitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Submit", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.SubmitRequestBody Body;
        
        public SubmitRequest() {
        }
        
        public SubmitRequest(ConsoleApplication1.ServiceReference1.SubmitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference1.TaskInst taskinst;
        
        public SubmitRequestBody() {
        }
        
        public SubmitRequestBody(ConsoleApplication1.ServiceReference1.TaskInst taskinst) {
            this.taskinst = taskinst;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReference1.SubmitResponseBody Body;
        
        public SubmitResponse() {
        }
        
        public SubmitResponse(ConsoleApplication1.ServiceReference1.SubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nextApprover;
        
        public SubmitResponseBody() {
        }
        
        public SubmitResponseBody(string SubmitResult, string nextApprover) {
            this.SubmitResult = SubmitResult;
            this.nextApprover = nextApprover;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WFServiceSoapChannel : ConsoleApplication1.ServiceReference1.WFServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WFServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.WFServiceSoap>, ConsoleApplication1.ServiceReference1.WFServiceSoap {
        
        public WFServiceSoapClient() {
        }
        
        public WFServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WFServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.SubmitResponse ConsoleApplication1.ServiceReference1.WFServiceSoap.Submit(ConsoleApplication1.ServiceReference1.SubmitRequest request) {
            return base.Channel.Submit(request);
        }
        
        public string Submit(ConsoleApplication1.ServiceReference1.TaskInst taskinst, out string nextApprover) {
            ConsoleApplication1.ServiceReference1.SubmitRequest inValue = new ConsoleApplication1.ServiceReference1.SubmitRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.SubmitRequestBody();
            inValue.Body.taskinst = taskinst;
            ConsoleApplication1.ServiceReference1.SubmitResponse retVal = ((ConsoleApplication1.ServiceReference1.WFServiceSoap)(this)).Submit(inValue);
            nextApprover = retVal.Body.nextApprover;
            return retVal.Body.SubmitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.SubmitResponse> ConsoleApplication1.ServiceReference1.WFServiceSoap.SubmitAsync(ConsoleApplication1.ServiceReference1.SubmitRequest request) {
            return base.Channel.SubmitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.SubmitResponse> SubmitAsync(ConsoleApplication1.ServiceReference1.TaskInst taskinst) {
            ConsoleApplication1.ServiceReference1.SubmitRequest inValue = new ConsoleApplication1.ServiceReference1.SubmitRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference1.SubmitRequestBody();
            inValue.Body.taskinst = taskinst;
            return ((ConsoleApplication1.ServiceReference1.WFServiceSoap)(this)).SubmitAsync(inValue);
        }
    }
}
