//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuZiYangNote.MultiLanguageConfig {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonCnOrEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonCnOrEn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuZiYangNote.MultiLanguageConfig.CommonCnOrEn", typeof(CommonCnOrEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string CloseCn {
            get {
                return ResourceManager.GetString("CloseCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closed 的本地化字符串。
        /// </summary>
        internal static string CloseEn {
            get {
                return ResourceManager.GetString("CloseEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”界面已打开！是否设置最前显示？ 的本地化字符串。
        /// </summary>
        internal static string IsWidowsOpenCn {
            get {
                return ResourceManager.GetString("IsWidowsOpenCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”The interface is open! Do you want to set the top display? 的本地化字符串。
        /// </summary>
        internal static string IsWidowsOpenEn {
            get {
                return ResourceManager.GetString("IsWidowsOpenEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}！暂未配置中文信息！ 的本地化字符串。
        /// </summary>
        internal static string LanguageErrorCn {
            get {
                return ResourceManager.GetString("LanguageErrorCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}！English information is not configured yet！ 的本地化字符串。
        /// </summary>
        internal static string LanguageErrorEn {
            get {
                return ResourceManager.GetString("LanguageErrorEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string OpenCn {
            get {
                return ResourceManager.GetString("OpenCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opened 的本地化字符串。
        /// </summary>
        internal static string OpenEn {
            get {
                return ResourceManager.GetString("OpenEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string PromptCn {
            get {
                return ResourceManager.GetString("PromptCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        internal static string PromptEn {
            get {
                return ResourceManager.GetString("PromptEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已将窗体”{0}“设置最前显示！ 的本地化字符串。
        /// </summary>
        internal static string WidowShow01Cn {
            get {
                return ResourceManager.GetString("WidowShow01Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The form &quot;{0}&quot; has been set to the first display! 的本地化字符串。
        /// </summary>
        internal static string WidowShow01En {
            get {
                return ResourceManager.GetString("WidowShow01En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已将窗体”{0}“{1}！ 的本地化字符串。
        /// </summary>
        internal static string WidowShow02Cn {
            get {
                return ResourceManager.GetString("WidowShow02Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form &quot;{0}&quot; has been {1}！ 的本地化字符串。
        /// </summary>
        internal static string WidowShow02En {
            get {
                return ResourceManager.GetString("WidowShow02En", resourceCulture);
            }
        }
    }
}
