//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuZiYangNote.MultiLanguageConfig {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MdiFormCnOrEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MdiFormCnOrEn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MuZiYangNote.MultiLanguageConfig.MdiFormCnOrEn", typeof(MdiFormCnOrEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添 加 的本地化字符串。
        /// </summary>
        internal static string btnAddTaskCn {
            get {
                return ResourceManager.GetString("btnAddTaskCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string btnAddTaskEn {
            get {
                return ResourceManager.GetString("btnAddTaskEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换展示 的本地化字符串。
        /// </summary>
        internal static string btnShowTypeCn {
            get {
                return ResourceManager.GetString("btnShowTypeCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Display 的本地化字符串。
        /// </summary>
        internal static string btnShowTypeEn {
            get {
                return ResourceManager.GetString("btnShowTypeEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平铺模式 的本地化字符串。
        /// </summary>
        internal static string gpbTaskListCn {
            get {
                return ResourceManager.GetString("gpbTaskListCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Pattern 的本地化字符串。
        /// </summary>
        internal static string gpbTaskListEn {
            get {
                return ResourceManager.GetString("gpbTaskListEn", resourceCulture);
            }
        }
    }
}
